# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.5
_src_path: https://github.com/jupyterlab/extension-template
advanced: false
author_email: brian.y.soong@gmail.com
author_name: Brian Soong
has_ai_rules: false
has_binder: false
has_settings: true
kind: theme
labextension_name: jupyterlab-monokai-pro-ce
project_short_description: Monokai Pro (CE) dark and light themes for JupyterLab
python_name: jupyterlab_monokai_pro_ce
repository: https://github.com/brianysoong/monokai-pro-jupyterlab
test: false

