"""Generate style/codicons.css from the vendored Codicons in style/codicons/.

Run after changing MAPPING or updating the SVGs:

    python scripts/build_codicons.py

Each mapped JupyterLab icon (matched by its LabIcon name in the `data-icon`
attribute) keeps its element but hides its own artwork and paints the
Codicon instead, using the text color, as VS Code does. Pure CSS keeps the
swap immune to other code re-registering icons, and toggles with the
`data-mpce-codicons` attribute.
"""

from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
SVG_DIR = ROOT / "style" / "codicons"

# JupyterLab icon name (ui-components:<name>) -> Codicon file
MAPPING = {
    "add": "add",
    "bell": "bell",
    "bug": "debug",
    "build": "tools",
    "caret-down": "chevron-down",
    "caret-up": "chevron-up",
    "caret-left": "chevron-left",
    "caret-right": "chevron-right",
    "caret-down-empty": "triangle-down",
    "caret-down-empty-thin": "chevron-down",
    "check": "check",
    "cleaning": "clear-all",
    "close": "close",
    "close-all": "close-all",
    "code": "code",
    "collapse-all": "collapse-all",
    "copy": "copy",
    "delete": "trash",
    "download": "cloud-download",
    "ellipses": "ellipsis",
    "extension": "extensions",
    "fast-forward": "run-all",
    "file": "file",
    "file-upload": "cloud-upload",
    "filter": "filter",
    "folder": "folder",
    "home": "home",
    "info": "info",
    "keyboard": "record-keys",
    "launch": "link-external",
    "list": "list-flat",
    "move-down": "arrow-down",
    "move-up": "arrow-up",
    "new-folder": "new-folder",
    "numbering": "list-ordered",
    "palette": "symbol-color",
    "paste": "clippy",
    "pause": "debug-pause",
    "redo": "redo",
    "refresh": "refresh",
    "run": "play",
    "running": "stop-circle",
    "save": "save",
    "search": "search",
    "settings": "settings-gear",
    "step-into": "debug-step-into",
    "step-out": "debug-step-out",
    "step-over": "debug-step-over",
    "stop": "primitive-square",
    "table-rows": "list-flat",
    "toc": "list-unordered",
    "tree-view": "list-tree",
    "undo": "discard",
}

HEADER = """\
/* -----------------------------------------------------------------------------
| Codicons for the Modern UI. Generated by scripts/build_codicons.py; edit
| the mapping there, not this file.
|
| Codicons (c) Microsoft Corporation, licensed under CC BY 4.0
| (style/codicons/LICENSE). Icons are recolored to the surrounding text.
|---------------------------------------------------------------------------- */
"""


# Places where the surrounding text color is the wrong color for the icon
CONTEXT = """\
/* Buttons filled with the accept color, e.g. the file browser's
   new-launcher button */
:root[data-mpce-codicons] jp-button[appearance='accent'],
:root[data-mpce-codicons]
  .jp-ToolbarButtonComponent[data-command='launcher:create'] {
  color: var(--mpce-on-highlight, var(--jp-ui-inverse-font-color0));
}

/* A tab with unsaved changes shows JupyterLab's dot in place of the close
   icon until hovered (VS Code does the same); hand it back JupyterLab's own
   artwork, which draws the dot */
:root[data-mpce-codicons]
  .lm-TabBar-tab.jp-mod-dirty
  > .lm-TabBar-tabCloseIcon
  > svg:not(:hover) {
  background: none;
  mask: none;
}

:root[data-mpce-codicons]
  .lm-TabBar-tab.jp-mod-dirty
  > .lm-TabBar-tabCloseIcon
  > svg:not(:hover)
  > :is(path, g, circle, ellipse, rect, line, polyline, polygon) {
  visibility: visible;
}

/* Tab close buttons keep the plain icon color, not the tab's highlight */
:root[data-mpce-codicons] .lm-TabBar-tabCloseIcon {
  color: var(--jp-ui-font-color1);
}
"""


# Elements that make up JupyterLab's own icon artwork, hidden under the
# Codicon. Named rather than matched with `*`: the browser checks rules ending
# in `*` against every element it restyles, such as each keystroke's spans.
ARTWORK = ("path", "g", "circle", "ellipse", "rect", "line", "polyline", "polygon")


def data_uri(svg: str) -> str:
    svg = " ".join(svg.split()).replace('"', "'")
    return 'url("data:image/svg+xml,' + quote(svg, safe=" '=/:;,.-") + '")'


def main() -> None:
    names = sorted(MAPPING)
    selector = lambda n: f"svg[data-icon='ui-components:{n}']"
    all_icons = ",\n".join(f":root[data-mpce-codicons] {selector(n)}" for n in names)
    children = ",\n".join(
        f":root[data-mpce-codicons] {selector(n)} > {tag}"
        for n in names
        for tag in ARTWORK
    )

    out = [HEADER]
    out.append(f"{all_icons} {{\n  background-color: currentcolor;\n"
               "  mask: var(--mpce-codicon) center / contain no-repeat;\n}\n")
    out.append(f"{children} {{\n  visibility: hidden;\n}}\n")
    for name in names:
        svg = (SVG_DIR / f"{MAPPING[name]}.svg").read_text()
        out.append(f":root[data-mpce-codicons] {selector(name)} {{\n"
                   f"  --mpce-codicon: {data_uri(svg)};\n}}\n")
    out.append(CONTEXT)
    (ROOT / "style" / "codicons.css").write_text("\n".join(out))
    print(f"wrote style/codicons.css ({len(names)} icons)")


if __name__ == "__main__":
    main()
